[package]
name = "stalk"
version = "0.1.0"
authors = ["Jeremiah A. Bohling <jeremiah.bohling@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
